version: '3.8'
services:
  api-tests-dev:
    build: .
    image: alexapostu/api-tests:latest
    container_name: api-test-dev
    volumes:
      - $PWD/test-reports/dev:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run greeting greetings_dev
  api-tests-stg:
    build: .
    image: alexapostu/api-tests:latest
    container_name: api-test-stg
    volumes:
      - $PWD/test-reports/stg:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run greeting greetings_stg
  api-tests-prd:
    build: .
    image: alexapostu/api-tests:latest
    container_name: api-test-prd
    volumes:
      - $PWD/test-reports/prd:/api-test-automation/mochawesome-report/
    network_mode: host
    command: run greeting greetings_prod


# docker run -v $PWD/test-reports:/api-test-automation/mochawesome-report/ --network=host --rm api-tests run BOOKS BOOKS_DEV0.2